### ISSUE TITLE
KeyError upon calling sb.matches() for open data

### ISSUE THREAD

**Issue by kevidigi** [statsbomb/statsbombpy#8]
Runnning something like:

```
from statsbombpy import sb


matches = sb.matches(16,4)
```

Produces the output:

```
credentials were not supplied. open data access only
Traceback (most recent call last):

  File "/Users/user/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)

  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc

  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc

  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item

  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item

KeyError: 'stadium'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File ".../code/python/extract_statsbomb_data.py", line 13, in <module>
    matches = sb.matches(16,4)

  File "/Users/user/.pyenv/versions/3.8.2/lib/python3.8/site-packages/statsbombpy/sb.py", line 40, in matches
    matches[col] = matches[col].apply(

  File "/Users/user/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pandas/core/frame.py", line 2902, in __getitem__
    indexer = self.columns.get_loc(key)

  File "/Users/user/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    raise KeyError(key) from err

KeyError: 'stadium'
```

Looking at the open data, some of the matches don't appear to have a stadium listed - I suppose that either a) they should or b) statsbombpy should handle this.

I suppose a workaround in the meantime is to call `sb.matches(i, j, fmt="dict")` (importing the data as a dictionary) and then use pandas to create a dataframe.

Apologies in advance if I'm missing something!

**Comment by ElJdP** [comment]
I think you're about right. It seems to be that season/comp only. I've tried  w/ every other and they seem to work fine.
